<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net9.0;netstandard2.0</TargetFrameworks>
    <AssemblyName>Should.Fluent</AssemblyName>
    <RootNamespace>Should.Fluent</RootNamespace>
    <IsPackable>true</IsPackable>
    <PackageId>ShouldFluent</PackageId>
    <Description>Fluent assertion API for the Should Assertion Library. Test runner agnostic.</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Should.Core\Should.Core.csproj" />
  </ItemGroup>
</Project>
